name: Redeploy AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      # Передача только чувствительных переменных через GitHub Secrets
      TF_VAR_ec2_ssh_public_key: ${{ secrets.EC2_SSH_PUBLIC_KEY }}
      TF_VAR_ec2_private_key: ${{ secrets.EC2_PRIVATE_KEY }}
      AWS_REGION: eu-north-1

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # 3. Настраиваем AWS CLI с ключами и регионом
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # 4. Инициализация Terraform (локально без backend)
      - name: Terraform Init
        run: terraform init

      # 5. Создание S3 backend для состояния Terraform
      - name: Terraform Apply backend
        run: terraform apply -auto-approve -target=local_file.backend_config

      # 6. Инициализация Terraform с backend
      - name: Terraform Init with backend
        run: terraform init -backend-config=backend.config -force-copy

      # 7. Деплой инфраструктуры
      - name: Terraform Apply infra
        run: terraform apply -auto-approve
